SUBJECTS_BY_LEVEL = {
    'BASICO': [
        'Lenguaje',
        'Lengua y cultura de pueblos originarios',
        'Matemáticas',
        'Historia',
        'Ciencias',
        'Inglés',
        'Artes',
        'Tecnología',
        'Música',
        'Educación Física',
        'Religión',
        'Orientación',
        'TMMCO',
        'Tutoría',
        'Taller de competencias socioemocionales',
        'Taller de acondicionamiento físico',
        'Taller de artes',
        'Taller de música',
        'Taller de inglés',
        'Taller de tecnología',
        'Taller de lectoescritura',
    ],
    'MEDIO_1_2': [
        'Lenguaje',
        'Matemáticas',
        'Historia',
        'Biología',
        'Química',
        'Física',
        'Inglés',
        'Tecnología',
        'Artes',
        'Música',
        'Educación Física',
        'Religión',
        'Orientación',
        'Taller de Ciencias',
        'TAF',
        'Taller de competencias socioemocionales',
        'TMMCO',
        'Tutoría',
    ],
    'MEDIO_3_4': [
        'Lenguaje',
        'Matemáticas',
        'Educación Ciudadana',
        'Ciencias para la Ciudadanía',
        'Filosofía',
        'Inglés',
        'Religión',
        'Orientación',
        'Taller de Historia',
        'TAF',
        'Taller de competencias socioemocionales',
        'TMMCO',
        'Tutoría',
        'Participación y argumentación en democracia',
        'Comprensión histórica del presente',
        'Geografía, territorio y desafíos socioambientales',
        'Física',
        'Probabilidades y estadísticas',
        'Geometría 3D',
        'Ciencias de la salud',
        'Biología celular y molecular',
        'Química',
        'Ciencias del ejercicio físico y deportivo',
        'Arquitectura y diseño',
        'Interpretación musical',
    ],
}
