SUBJECTS_BY_LEVEL = {
    'BASICO': [
        'Ciencias',
        'Matemáticas',
        'Educación Física',
        'Lenguaje',
        'Inglés',
        'Artes',
        'Tecnología',
        'Música',
        'Religión',
        'Historia',
        'Orientación',
    ],
    'MEDIO_1_2': [
        'Inglés',
        'Tutoría',
        'Matemáticas',
        'Educación Física',
        'Lenguaje',
        'Biología',
        'Historia',
        'Física',
        'Química',
        'Artes',
        'Tecnología',
        'Religión',
        'Orientación',
    ],
    'MEDIO_3_4': [
        'Tutoría',
        'Lenguaje',
        'Inglés',
        'Matemáticas',
        'Módulo Geo3D',
        'Taller Historia',
        'Ciencias para la Ciudadanía',
        'Módulo CompHist',
        'Módulo InterpMus',
        'TAF',
        'Filosofía',
    ],
}
